# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ruby' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ruby
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'

  target 'RubyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Ruby-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ruby-tvOS

  target 'Ruby-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
